#!/bin/bash

echo "🔍 Role-Based Access Control Setup Guide"
echo "=========================================="
echo ""

echo "1️⃣  SETUP BACKEND TEST DATA"
echo "   Run the seed script to create test users with proper passwords:"
echo ""
echo "   cd backend"
echo "   npm run seed:class"
echo ""
echo "   This will create:"
echo "   ✅ teacher-demo (password: Teacher123!, role: TEACHER)"
echo "   ✅ student-demo (password: Student123!, role: STUDENT)"
echo ""

echo "2️⃣  TEST API LOGIN"
echo "   Run the API test to verify backend is working:"
echo ""
echo "   cd .."
echo "   node test-role-access.mjs"
echo ""
echo "   Expected output:"
echo "   ✅ Login successful for teacher-demo with role TEACHER"
echo "   ✅ Login successful for student-demo with role STUDENT"
echo ""

echo "3️⃣  TEST FRONTEND UI"
echo "   Start frontend and test in browser:"
echo ""
echo "   Terminal 1 (Backend):"
echo "   cd backend && npm run dev"
echo ""
echo "   Terminal 2 (Frontend):"
echo "   cd frontend && npm run dev"
echo ""
echo "   Then:"
echo "   a) Go to http://localhost:5173/login"
echo "   b) Click 'Teacher Demo' button"
echo "   c) Verify you see 8 tabs (including จัดการนักเรียน, สร้างงาน, ตั้งค่า)"
echo "   d) Logout and click 'Student Demo' button"
echo "   e) Verify you see only 5 tabs (no teacher-only tabs)"
echo ""

echo "4️⃣  VERIFY TAB VISIBILITY"
echo ""
echo "   TEACHER (8 tabs total):"
echo "   ✅ ภาพรวม (Overview)"
echo "   ✅ งานที่ได้รับมอบหมาย (Assignments)"
echo "   ✅ การเข้าเรียน (Attendance)"
echo "   ✅ ประกาศ (Announcements)"
echo "   ✅ ตารางเรียน (Schedule)"
echo "   ✅ จัดการนักเรียน (Manage Students) ← TEACHER ONLY"
echo "   ✅ สร้างงาน (Create Assignments) ← TEACHER ONLY"
echo "   ✅ ตั้งค่า (Settings) ← TEACHER ONLY"
echo ""
echo "   STUDENT (5 tabs total):"
echo "   ✅ ภาพรวม (Overview)"
echo "   ✅ งานที่ได้รับมอบหมาย (Assignments)"
echo "   ✅ การเข้าเรียน (Attendance)"
echo "   ✅ ประกาศ (Announcements)"
echo "   ✅ ตารางเรียน (Schedule)"
echo "   ❌ Teacher-only tabs NOT visible"
echo ""

echo "=========================================="
echo "Done! Role-based access should now work correctly."
echo "=========================================="
